"""Tests for ``tools/make_pot.py``, the standard-library gettext extractor.

The project builds on Windows, where GNU ``xgettext`` is not present, so the
``.pot`` template is regenerated by this AST-based extractor instead. Parsing
rather than text-scanning is the whole point: a ``_("...")`` in a docstring is
not a call and must be ignored, a call split over lines must still be found, and
a ``_(variable)`` the extractor cannot read must warn rather than vanish. All of
that is pure -- source in, messages and warnings out -- so it is driven directly,
with ``main`` exercised against temp sources and a temp output so the real
template is never touched.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools.make_pot import (
    Message,
    _call_name,
    _escape,
    _format_entry,
    _iter_sources,
    _literal,
    _project_version,
    _strip_creation_date,
    build_pot,
    extract_file,
    main,
)

_ROOT = Path(__file__).resolve().parent.parent


def _expr(code: str) -> ast.expr:
    return ast.parse(code, mode="eval").body


def _extract(tmp_path: Path, source: str) -> tuple[dict, list[str]]:
    path = tmp_path / "mod.py"
    path.write_text(source, encoding="utf-8")
    messages: dict = {}
    warnings = extract_file(path, tmp_path, messages)
    return messages, warnings


class TestLiteralAndCallName:
    def test_a_string_literal_is_returned(self) -> None:
        assert _literal(_expr('"hello"')) == "hello"

    def test_a_non_string_constant_is_not_a_literal(self) -> None:
        assert _literal(_expr("42")) is None

    def test_a_variable_is_not_a_literal(self) -> None:
        assert _literal(_expr("name")) is None

    def test_a_bare_call_name(self) -> None:
        assert _call_name(_expr('_("x")')) == "_"

    def test_an_attribute_call_name_drops_the_path(self) -> None:
        assert _call_name(_expr('i18n.gettext("x")')) == "gettext"

    def test_an_unnameable_call_is_none(self) -> None:
        assert _call_name(_expr('funcs["k"]("x")')) is None  # a subscript, not a name


class TestExtractFile:
    def test_a_gettext_call_is_collected_with_its_location(self, tmp_path: Path) -> None:
        messages, warnings = _extract(tmp_path, '_("Hello")\n')
        assert warnings == []
        assert ("Hello", None) in messages
        assert messages[("Hello", None)].locations == [("mod.py", 1)]

    def test_an_ngettext_call_records_both_forms(self, tmp_path: Path) -> None:
        messages, _ = _extract(tmp_path, 'ngettext("%(n)d file", "%(n)d files", n)\n')
        assert ("%(n)d file", "%(n)d files") in messages

    def test_a_string_in_a_docstring_is_not_a_call(self, tmp_path: Path) -> None:
        """The AST approach ignores ``_("x")`` written inside prose."""
        messages, warnings = _extract(tmp_path, '"""Not a call: _(\\"x\\")."""\n')
        assert messages == {}
        assert warnings == []

    def test_a_non_literal_marker_warns(self, tmp_path: Path) -> None:
        _messages, warnings = _extract(tmp_path, "_(variable)\n")
        assert warnings and "non-literal" in warnings[0]

    def test_an_ngettext_with_a_non_literal_plural_warns(self, tmp_path: Path) -> None:
        _messages, warnings = _extract(tmp_path, 'ngettext("one", plural_var, n)\n')
        assert warnings and "plural is not a literal" in warnings[0]

    def test_a_marker_with_no_arguments_is_skipped(self, tmp_path: Path) -> None:
        messages, warnings = _extract(tmp_path, "_()\n")
        assert messages == {} and warnings == []

    def test_a_non_marker_call_is_skipped(self, tmp_path: Path) -> None:
        messages, warnings = _extract(tmp_path, 'print("x")\n')
        assert messages == {} and warnings == []

    def test_a_syntax_error_is_reported_not_raised(self, tmp_path: Path) -> None:
        path = tmp_path / "bad.py"
        path.write_text("def (:\n", encoding="utf-8")
        warnings = extract_file(path, tmp_path, {})
        assert warnings and "could not parse" in warnings[0]

    def test_the_same_string_in_two_places_gets_two_locations(self, tmp_path: Path) -> None:
        messages, _ = _extract(tmp_path, '_("Hi")\n_("Hi")\n')
        assert len(messages[("Hi", None)].locations) == 2


class TestEscapeAndFormat:
    def test_escape_handles_the_po_special_characters(self) -> None:
        assert _escape('a\\b"c\nd\te') == 'a\\\\b\\"c\\nd\\te'

    def test_a_singular_entry_has_an_empty_msgstr(self) -> None:
        msg = Message("Hello", None)
        msg.locations = [("mod.py", 3)]
        entry = _format_entry(msg)
        assert "#: mod.py:3" in entry
        assert 'msgid "Hello"' in entry
        assert entry.endswith('msgstr ""')

    def test_a_plural_entry_has_indexed_msgstrs(self) -> None:
        msg = Message("%(n)d file", "%(n)d files")
        msg.locations = [("mod.py", 1)]
        entry = _format_entry(msg)
        assert "msgid_plural" in entry
        assert 'msgstr[0] ""' in entry and 'msgstr[1] ""' in entry


class TestBuildPot:
    def test_an_empty_message_set_is_just_the_header(self) -> None:
        pot = build_pot({}, "9.9.9")
        assert "Project-Id-Version: Wraithguard Toolkit 9.9.9" in pot
        assert "POT-Creation-Date:" in pot
        assert "msgid_plural" not in pot  # no entries

    def test_entries_are_ordered_by_first_location(self) -> None:
        early, late = Message("early", None), Message("late", None)
        early.locations = [("a.py", 1)]
        late.locations = [("a.py", 9)]
        pot = build_pot({("late", None): late, ("early", None): early}, "1.0")
        assert pot.index('msgid "early"') < pot.index('msgid "late"')


class TestHelpers:
    def test_iter_sources_expands_directories_and_skips_pycache(self, tmp_path: Path) -> None:
        (tmp_path / "a.py").write_text("", encoding="utf-8")
        (tmp_path / "note.txt").write_text("", encoding="utf-8")
        (tmp_path / "__pycache__").mkdir()
        (tmp_path / "__pycache__" / "b.py").write_text("", encoding="utf-8")
        assert [p.name for p in _iter_sources([tmp_path])] == ["a.py"]

    def test_project_version_reads_the_dunder(self, tmp_path: Path) -> None:
        pkg = tmp_path / "wraithguard"
        pkg.mkdir()
        (pkg / "__init__.py").write_text('__version__ = "3.1.8"\n', encoding="utf-8")
        assert _project_version(tmp_path) == "3.1.8"

    def test_project_version_is_a_question_mark_when_absent(self, tmp_path: Path) -> None:
        assert _project_version(tmp_path) == "?"

    def test_project_version_is_a_question_mark_without_the_dunder(self, tmp_path: Path) -> None:
        """An __init__ that exists but declares no __version__ still yields '?'."""
        pkg = tmp_path / "wraithguard"
        pkg.mkdir()
        (pkg / "__init__.py").write_text("# no version here\nx = 1\n", encoding="utf-8")
        assert _project_version(tmp_path) == "?"

    def test_strip_creation_date_removes_only_that_line(self) -> None:
        text = '"POT-Creation-Date: 2026\\n"\n"Language: \\n"'
        assert "POT-Creation-Date" not in _strip_creation_date(text)
        assert "Language" in _strip_creation_date(text)


class TestMain:
    def test_no_sources_found_fails(self, tmp_path: Path, capsys) -> None:
        assert main([str(tmp_path / "nothing.txt"), "-o", str(tmp_path / "out.pot")]) == 1
        assert "no Python sources" in capsys.readouterr().err

    def test_a_clean_write_succeeds(self, tmp_path: Path, capsys) -> None:
        src = tmp_path / "s.py"
        src.write_text('_("Hello")\n', encoding="utf-8")
        out = tmp_path / "out.pot"
        assert main([str(src), "-o", str(out)]) == 0
        assert out.is_file()
        assert 'msgid "Hello"' in out.read_text(encoding="utf-8")
        assert "wrote" in capsys.readouterr().out

    def test_a_warning_makes_the_write_return_one(self, tmp_path: Path, capsys) -> None:
        src = tmp_path / "s.py"
        src.write_text("_(variable)\n", encoding="utf-8")
        out = tmp_path / "out.pot"
        assert main([str(src), "-o", str(out)]) == 1
        assert "WARNING" in capsys.readouterr().err

    def test_an_empty_template_notes_that_nothing_is_marked(self, tmp_path: Path, capsys) -> None:
        src = tmp_path / "s.py"
        src.write_text("x = 1\n", encoding="utf-8")
        out = tmp_path / "out.pot"
        assert main([str(src), "-o", str(out)]) == 0
        assert "no strings are marked" in capsys.readouterr().err

    def test_check_passes_when_the_template_is_current(self, tmp_path: Path, capsys) -> None:
        src = tmp_path / "s.py"
        src.write_text('_("Hello")\n', encoding="utf-8")
        out = tmp_path / "out.pot"
        assert main([str(src), "-o", str(out)]) == 0  # write it first
        capsys.readouterr()
        assert main([str(src), "-o", str(out), "--check"]) == 0
        assert "up to date" in capsys.readouterr().out

    def test_check_fails_when_the_template_is_stale(self, tmp_path: Path, capsys) -> None:
        src = tmp_path / "s.py"
        src.write_text('_("Hello")\n', encoding="utf-8")
        out = tmp_path / "out.pot"
        assert main([str(src), "-o", str(out)]) == 0
        src.write_text('_("Hello")\n_("Added later")\n', encoding="utf-8")
        assert main([str(src), "-o", str(out), "--check"]) == 1
        assert "out of date" in capsys.readouterr().err

    def test_check_fails_when_the_template_is_missing(self, tmp_path: Path, capsys) -> None:
        src = tmp_path / "s.py"
        src.write_text('_("Hello")\n', encoding="utf-8")
        assert main([str(src), "-o", str(tmp_path / "absent.pot"), "--check"]) == 1
        assert "does not exist" in capsys.readouterr().err

    def test_the_i18n_module_is_excluded_from_scanning(self, tmp_path: Path) -> None:
        """Passing the real ``wraithguard/i18n.py`` as a target skips it silently."""
        out = tmp_path / "out.pot"
        i18n = _ROOT / "wraithguard" / "i18n.py"
        in_root = _ROOT / "wraithguard" / "__init__.py"  # in-root, not excluded: scanned
        extra = tmp_path / "s.py"
        extra.write_text('_("Hello")\n', encoding="utf-8")
        assert main([str(i18n), str(in_root), str(extra), "-o", str(out)]) == 0
        text = out.read_text(encoding="utf-8")
        assert 'msgid "Hello"' in text  # the extra file was scanned, i18n.py was not
