"""Known enum variants for TES3 record fields, for the patch value dropdown.

The variants themselves live in :mod:`wraithguard.patch.enum_data`, generated by
``tools/gen_tes3_enums.py`` from tes3conv's output for the vanilla masters -- so
the spellings are the crate's own, not transcribed by hand (which had already
mis-guessed ``enchant_type`` and ``apparatus_type``). This module is the lookup
over that table.

Best-effort by design, like the record schema. The dialog's combobox is
**editable** and always *also* offers the values the conflicting plugins
themselves use, so a field the table misses or over-includes is never a dead end
-- at worst the dropdown is shorter or longer, never wrong. Keyed by the *leaf*
field name (the last dotted path component), since an enum field keeps its name
across the records using it; a wrong key simply never matches.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from wraithguard.patch.enum_data import FIELD_ENUMS

if TYPE_CHECKING:
    from collections.abc import Sequence


def enum_options(path: str) -> tuple[str, ...]:
    """The known enum variants for a field path, or empty when none are known.

    Args:
        path: The flattened field name, e.g. ``data.spell_type``.

    Returns:
        The variant tuple for the field's leaf name, or ``()``.
    """
    return FIELD_ENUMS.get(path.rsplit(".", 1)[-1], ())


def value_options(current: object, present: bool, observed: Sequence[str], path: str) -> list[str]:
    """The dropdown list for a string field, de-duplicated and ordered.

    The field's own current value comes first (so it is pre-selected), then the
    known enum variants, then any other values the conflicting plugins use --
    the last of which are always valid, which is what keeps the list honest even
    where :data:`FIELD_ENUMS` has nothing to say.

    Args:
        current: The field's current value.
        present: Whether the field exists in the record.
        observed: String values other plugins use for this field.
        path: The flattened field name, for the enum lookup.

    Returns:
        The options, in order, with no duplicates. Empty unless the field is a
        present string or a variant/observed value exists.
    """
    out: list[str] = []
    if present and isinstance(current, str):
        out.append(current)
    for value in (*enum_options(path), *observed):
        if value not in out:
            out.append(value)
    return out
