"""TES3 field types by record and path -- GENERATED, do not edit by hand.

See ``tools/gen_tes3_fieldtypes.py``, which reads the tes3 crate. Each kind is
one of: ``float``, ``int:<min>:<max>``, ``str``, ``bool``, ``enum``,
``flags:<FlagsName>``, or ``list``.
"""

from __future__ import annotations

from typing import Final

#: 43 record types -> flattened field path -> kind.
RECORD_FIELDS: Final[dict[str, dict[str, str]]] = {
    'Activator': {
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
    },
    'Alchemy': {
        'data.flags': 'flags:AlchemyFlags',
        'data.value': 'int:0:4294967295',
        'data.weight': 'float',
        'effects': 'list',
        'flags': 'flags:ObjectFlags',
        'icon': 'str',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
    },
    'Apparatus': {
        'data.apparatus_type': 'enum',
        'data.quality': 'float',
        'data.value': 'int:0:4294967295',
        'data.weight': 'float',
        'flags': 'flags:ObjectFlags',
        'icon': 'str',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
    },
    'Armor': {
        'biped_objects': 'list',
        'data.armor_rating': 'int:0:4294967295',
        'data.armor_type': 'enum',
        'data.enchantment': 'int:0:4294967295',
        'data.health': 'int:0:4294967295',
        'data.value': 'int:0:4294967295',
        'data.weight': 'float',
        'enchanting': 'str',
        'flags': 'flags:ObjectFlags',
        'icon': 'str',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
    },
    'Birthsign': {
        'description': 'str',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'name': 'str',
        'spells': 'list',
        'texture': 'str',
    },
    'Bodypart': {
        'data.bodypart_type': 'enum',
        'data.flags': 'flags:BodypartFlags',
        'data.part': 'enum',
        'data.vampire': 'bool',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'mesh': 'str',
        'race': 'str',
    },
    'Book': {
        'data.book_type': 'enum',
        'data.enchantment': 'int:0:4294967295',
        'data.skill': 'enum',
        'data.value': 'int:0:4294967295',
        'data.weight': 'float',
        'enchanting': 'str',
        'flags': 'flags:ObjectFlags',
        'icon': 'str',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
        'text': 'str',
    },
    'Cell': {
        'atmosphere_data.ambient_color': 'list',
        'atmosphere_data.fog_color': 'list',
        'atmosphere_data.fog_density': 'float',
        'atmosphere_data.sunlight_color': 'list',
        'data.flags': 'flags:CellFlags',
        'flags': 'flags:ObjectFlags',
        'map_color': 'list',
        'name': 'str',
        'region': 'str',
        'water_height': 'float',
    },
    'Class': {
        'data.attribute1': 'enum',
        'data.attribute2': 'enum',
        'data.flags': 'flags:ClassFlags',
        'data.major1': 'enum',
        'data.major2': 'enum',
        'data.major3': 'enum',
        'data.major4': 'enum',
        'data.major5': 'enum',
        'data.minor1': 'enum',
        'data.minor2': 'enum',
        'data.minor3': 'enum',
        'data.minor4': 'enum',
        'data.minor5': 'enum',
        'data.services': 'flags:ServiceFlags',
        'data.specialization': 'enum',
        'description': 'str',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'name': 'str',
    },
    'Clothing': {
        'biped_objects': 'list',
        'data.clothing_type': 'enum',
        'data.enchantment': 'int:0:65535',
        'data.value': 'int:0:65535',
        'data.weight': 'float',
        'enchanting': 'str',
        'flags': 'flags:ObjectFlags',
        'icon': 'str',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
    },
    'Container': {
        'container_flags': 'flags:ContainerFlags',
        'encumbrance': 'float',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'inventory': 'list',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
    },
    'Creature': {
        'ai_data.alarm': 'int:-128:127',
        'ai_data.fight': 'int:-128:127',
        'ai_data.flee': 'int:-128:127',
        'ai_data.hello': 'int:-32768:32767',
        'ai_data.services': 'flags:ServiceFlags',
        'ai_packages': 'list',
        'blood_type': 'int:0:255',
        'creature_flags': 'flags:CreatureFlags',
        'data.agility': 'int:0:4294967295',
        'data.combat': 'int:0:4294967295',
        'data.creature_type': 'enum',
        'data.endurance': 'int:0:4294967295',
        'data.fatigue': 'int:0:4294967295',
        'data.gold': 'int:0:4294967295',
        'data.health': 'int:0:4294967295',
        'data.intelligence': 'int:0:4294967295',
        'data.level': 'int:0:4294967295',
        'data.luck': 'int:0:4294967295',
        'data.magic': 'int:0:4294967295',
        'data.magicka': 'int:0:4294967295',
        'data.personality': 'int:0:4294967295',
        'data.soul': 'int:0:4294967295',
        'data.speed': 'int:0:4294967295',
        'data.stealth': 'int:0:4294967295',
        'data.strength': 'int:0:4294967295',
        'data.willpower': 'int:0:4294967295',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'inventory': 'list',
        'mesh': 'str',
        'name': 'str',
        'scale': 'float',
        'script': 'str',
        'sound': 'str',
        'spells': 'list',
        'travel_destinations': 'list',
    },
    'Dialogue': {
        'dialogue_type': 'enum',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
    },
    'DialogueInfo': {
        'data.dialogue_type': 'enum',
        'data.disposition': 'int:-2147483648:2147483647',
        'data.player_rank': 'int:-128:127',
        'data.speaker_rank': 'int:-128:127',
        'data.speaker_sex': 'enum',
        'filters': 'list',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'next_id': 'str',
        'player_faction': 'str',
        'prev_id': 'str',
        'quest_state': 'enum',
        'script_text': 'str',
        'sound_path': 'str',
        'speaker_cell': 'str',
        'speaker_class': 'str',
        'speaker_faction': 'str',
        'speaker_id': 'str',
        'speaker_race': 'str',
        'text': 'str',
    },
    'Door': {
        'close_sound': 'str',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'open_sound': 'str',
        'script': 'str',
    },
    'Enchanting': {
        'data.cost': 'int:0:4294967295',
        'data.enchant_type': 'enum',
        'data.flags': 'flags:EnchantingFlags',
        'data.max_charge': 'int:0:4294967295',
        'effects': 'list',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
    },
    'Faction': {
        'data.favored_attributes': 'list',
        'data.favored_skills': 'list',
        'data.flags': 'flags:FactionFlags',
        'data.requirements': 'list',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'name': 'str',
        'rank_names': 'list',
        'reactions': 'list',
    },
    'GameSetting': {
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'value': 'enum',
    },
    'GlobalVariable': {
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'value': 'enum',
    },
    'Header': {
        'file_type': 'enum',
        'flags': 'flags:ObjectFlags',
        'masters': 'list',
        'num_objects': 'int:0:4294967295',
        'version': 'float',
    },
    'Ingredient': {
        'data.attributes': 'list',
        'data.effects': 'list',
        'data.skills': 'list',
        'data.value': 'int:0:4294967295',
        'data.weight': 'float',
        'flags': 'flags:ObjectFlags',
        'icon': 'str',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
    },
    'Landscape': {
        'flags': 'flags:ObjectFlags',
        'landscape_flags': 'flags:LandscapeFlags',
        'texture_indices.data': 'list',
        'vertex_colors.data': 'list',
        'vertex_heights.data': 'list',
        'vertex_heights.offset': 'float',
        'vertex_normals.data': 'list',
        'world_map_data.data': 'list',
    },
    'LandscapeTexture': {
        'file_name': 'str',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'index': 'int:0:4294967295',
    },
    'LeveledCreature': {
        'chance_none': 'int:0:255',
        'creatures': 'list',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'leveled_creature_flags': 'flags:LeveledCreatureFlags',
    },
    'LeveledItem': {
        'chance_none': 'int:0:255',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'items': 'list',
        'leveled_item_flags': 'flags:LeveledItemFlags',
    },
    'Light': {
        'data.color': 'list',
        'data.flags': 'flags:LightFlags',
        'data.radius': 'int:0:4294967295',
        'data.time': 'int:-2147483648:2147483647',
        'data.value': 'int:0:4294967295',
        'data.weight': 'float',
        'flags': 'flags:ObjectFlags',
        'icon': 'str',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
        'sound': 'str',
    },
    'Lockpick': {
        'data.quality': 'float',
        'data.uses': 'int:0:4294967295',
        'data.value': 'int:0:4294967295',
        'data.weight': 'float',
        'flags': 'flags:ObjectFlags',
        'icon': 'str',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
    },
    'MagicEffect': {
        'area_sound': 'str',
        'area_visual': 'str',
        'bolt_sound': 'str',
        'bolt_visual': 'str',
        'cast_sound': 'str',
        'cast_visual': 'str',
        'data.base_cost': 'float',
        'data.flags': 'flags:MagicEffectFlags',
        'data.school': 'enum',
        'data.size': 'float',
        'data.size_cap': 'float',
        'data.speed': 'float',
        'description': 'str',
        'effect_id': 'enum',
        'flags': 'flags:ObjectFlags',
        'hit_sound': 'str',
        'hit_visual': 'str',
        'icon': 'str',
        'texture': 'str',
    },
    'MiscItem': {
        'data.flags': 'flags:MiscItemFlags',
        'data.value': 'int:0:4294967295',
        'data.weight': 'float',
        'flags': 'flags:ObjectFlags',
        'icon': 'str',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
    },
    'Npc': {
        'ai_data.alarm': 'int:-128:127',
        'ai_data.fight': 'int:-128:127',
        'ai_data.flee': 'int:-128:127',
        'ai_data.hello': 'int:-32768:32767',
        'ai_data.services': 'flags:ServiceFlags',
        'ai_packages': 'list',
        'blood_type': 'int:0:255',
        'class': 'str',
        'data.disposition': 'int:-128:127',
        'data.gold': 'int:0:4294967295',
        'data.level': 'int:-32768:32767',
        'data.rank': 'int:-128:127',
        'data.reputation': 'int:-128:127',
        'faction': 'str',
        'flags': 'flags:ObjectFlags',
        'hair': 'str',
        'head': 'str',
        'id': 'str',
        'inventory': 'list',
        'mesh': 'str',
        'name': 'str',
        'npc_flags': 'flags:NpcFlags',
        'race': 'str',
        'script': 'str',
        'spells': 'list',
        'travel_destinations': 'list',
    },
    'PathGrid': {
        'cell': 'str',
        'connections': 'list',
        'data.granularity': 'int:0:65535',
        'data.point_count': 'int:0:65535',
        'flags': 'flags:ObjectFlags',
        'points': 'list',
    },
    'Probe': {
        'data.quality': 'float',
        'data.uses': 'int:0:4294967295',
        'data.value': 'int:0:4294967295',
        'data.weight': 'float',
        'flags': 'flags:ObjectFlags',
        'icon': 'str',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
    },
    'Race': {
        'data.agility': 'list',
        'data.endurance': 'list',
        'data.flags': 'flags:RaceFlags',
        'data.height': 'list',
        'data.intelligence': 'list',
        'data.luck': 'list',
        'data.personality': 'list',
        'data.skill_bonuses.bonus_0': 'int:-2147483648:2147483647',
        'data.skill_bonuses.bonus_1': 'int:-2147483648:2147483647',
        'data.skill_bonuses.bonus_2': 'int:-2147483648:2147483647',
        'data.skill_bonuses.bonus_3': 'int:-2147483648:2147483647',
        'data.skill_bonuses.bonus_4': 'int:-2147483648:2147483647',
        'data.skill_bonuses.bonus_5': 'int:-2147483648:2147483647',
        'data.skill_bonuses.bonus_6': 'int:-2147483648:2147483647',
        'data.skill_bonuses.skill_0': 'enum',
        'data.skill_bonuses.skill_1': 'enum',
        'data.skill_bonuses.skill_2': 'enum',
        'data.skill_bonuses.skill_3': 'enum',
        'data.skill_bonuses.skill_4': 'enum',
        'data.skill_bonuses.skill_5': 'enum',
        'data.skill_bonuses.skill_6': 'enum',
        'data.speed': 'list',
        'data.strength': 'list',
        'data.weight': 'list',
        'data.willpower': 'list',
        'description': 'str',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'name': 'str',
        'spells': 'list',
    },
    'Region': {
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'map_color': 'list',
        'name': 'str',
        'sleep_creature': 'str',
        'sounds': 'list',
        'weather_chances.ash': 'int:0:255',
        'weather_chances.blight': 'int:0:255',
        'weather_chances.blizzard': 'int:0:255',
        'weather_chances.clear': 'int:0:255',
        'weather_chances.cloudy': 'int:0:255',
        'weather_chances.foggy': 'int:0:255',
        'weather_chances.overcast': 'int:0:255',
        'weather_chances.rain': 'int:0:255',
        'weather_chances.snow': 'int:0:255',
        'weather_chances.thunder': 'int:0:255',
    },
    'RepairItem': {
        'data.quality': 'float',
        'data.uses': 'int:0:4294967295',
        'data.value': 'int:0:4294967295',
        'data.weight': 'float',
        'flags': 'flags:ObjectFlags',
        'icon': 'str',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
    },
    'Script': {
        'bytecode': 'list',
        'flags': 'flags:ObjectFlags',
        'header.bytecode_length': 'int:0:4294967295',
        'header.num_floats': 'int:0:4294967295',
        'header.num_longs': 'int:0:4294967295',
        'header.num_shorts': 'int:0:4294967295',
        'header.variables_length': 'int:0:4294967295',
        'id': 'str',
        'text': 'str',
        'variables': 'list',
    },
    'Skill': {
        'data.actions': 'list',
        'data.governing_attribute': 'int:-2147483648:2147483647',
        'data.specialization': 'int:-2147483648:2147483647',
        'description': 'str',
        'flags': 'flags:ObjectFlags',
        'skill_id': 'enum',
    },
    'Sound': {
        'data.volume': 'int:0:255',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'sound_path': 'str',
    },
    'SoundGen': {
        'creature': 'str',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'sound': 'str',
        'sound_gen_type': 'enum',
    },
    'Spell': {
        'data.cost': 'int:0:4294967295',
        'data.flags': 'flags:SpellFlags',
        'data.spell_type': 'enum',
        'effects': 'list',
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'name': 'str',
    },
    'StartScript': {
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'script': 'str',
    },
    'Static': {
        'flags': 'flags:ObjectFlags',
        'id': 'str',
        'mesh': 'str',
    },
    'Weapon': {
        'data.chop_max': 'int:0:255',
        'data.chop_min': 'int:0:255',
        'data.enchantment': 'int:0:65535',
        'data.flags': 'flags:WeaponFlags',
        'data.health': 'int:0:65535',
        'data.reach': 'float',
        'data.slash_max': 'int:0:255',
        'data.slash_min': 'int:0:255',
        'data.speed': 'float',
        'data.thrust_max': 'int:0:255',
        'data.thrust_min': 'int:0:255',
        'data.value': 'int:0:4294967295',
        'data.weapon_type': 'enum',
        'data.weight': 'float',
        'enchanting': 'str',
        'flags': 'flags:ObjectFlags',
        'icon': 'str',
        'id': 'str',
        'mesh': 'str',
        'name': 'str',
        'script': 'str',
    },
}

#: 20 bitflags sets -> their flag names.
FLAG_VARIANTS: Final[dict[str, tuple[str, ...]]] = {
    'AlchemyFlags': ('AUTO_CALCULATE', ),
    'BodypartFlags': ('FEMALE', 'NOT_PLAYABLE', ),
    'CellFlags': ('IS_INTERIOR', 'HAS_WATER', 'RESTING_IS_ILLEGAL', 'BEHAVES_LIKE_EXTERIOR', ),
    'ClassFlags': ('PLAYABLE', ),
    'ContainerFlags': ('ORGANIC', 'RESPAWNS', 'IS_BASE', ),
    'CreatureFlags': ('BIPED', 'RESPAWN', 'WEAPON_AND_SHIELD', 'IS_BASE', 'SWIMS', 'FLIES', 'WALKS', 'ESSENTIAL', ),
    'EnchantingFlags': ('AUTO_CALCULATE', ),
    'FactionFlags': ('HIDDEN_FROM_PC', ),
    'LandscapeFlags': ('USES_VERTEX_HEIGHTS_AND_NORMALS', 'USES_VERTEX_COLORS', 'USES_TEXTURES', ),
    'LeveledCreatureFlags': ('CALCULATE_FROM_ALL_LEVELS', ),
    'LeveledItemFlags': ('CALCULATE_FOR_EACH_ITEM', 'CALCULATE_FROM_ALL_LEVELS', ),
    'LightFlags': ('DYNAMIC', 'CAN_CARRY', 'NEGATIVE', 'FLICKER', 'FIRE', 'OFF_BY_DEFAULT', 'FLICKER_SLOW', 'PULSE', 'PULSE_SLOW', ),
    'MagicEffectFlags': ('TARGET_SKILL', 'TARGET_ATTRIBUTE', 'NO_DURATION', 'NO_MAGNITUDE', 'HARMFUL', 'CONTINUOUS_VFX', 'CAN_CAST_SELF', 'CAN_CAST_TOUCH', 'CAN_CAST_TARGET', 'ALLOW_SPELLMAKING', 'ALLOW_ENCHANTING', 'NEGATIVE_LIGHTING', 'APPLIED_ONCE', 'UNKNOWN_CHAMELEON', 'NON_RECASTABLE', 'ILLEGAL_DAEDRA', 'UNREFLECTABLE', 'CASTER_LINKED', ),
    'MiscItemFlags': ('KEY', ),
    'NpcFlags': ('FEMALE', 'ESSENTIAL', 'RESPAWN', 'IS_BASE', 'AUTO_CALCULATE', ),
    'ObjectFlags': ('MODIFIED', 'DELETED', 'PERSISTENT', 'IGNORED', 'BLOCKED', ),
    'RaceFlags': ('PLAYABLE', 'BEAST_RACE', ),
    'ServiceFlags': ('BARTERS_WEAPONS', 'BARTERS_ARMOR', 'BARTERS_CLOTHING', 'BARTERS_BOOKS', 'BARTERS_INGREDIENTS', 'BARTERS_LOCKPICKS', 'BARTERS_PROBES', 'BARTERS_LIGHTS', 'BARTERS_APPARATUS', 'BARTERS_REPAIR_ITEMS', 'BARTERS_MISC_ITEMS', 'OFFERS_SPELLS', 'BARTERS_ENCHANTED_ITEMS', 'BARTERS_ALCHEMY', 'OFFERS_TRAINING', 'OFFERS_SPELLMAKING', 'OFFERS_ENCHANTING', 'OFFERS_REPAIRS', ),
    'SpellFlags': ('AUTO_CALCULATE', 'PC_START_SPELL', 'ALWAYS_SUCCEEDS', ),
    'WeaponFlags': ('IGNORES_NORMAL_WEAPON_RESISTANCE', 'SILVER', ),
}
